---
# This is used while preprocessing parquet stream
autoencoder:
  encoding_dim: 30
  epochs: 100
  learning_rate: 0.001

# List of models to train in the training flow
train_models:
- autoencoder_ensemble
- plain_ensemble
- naive_ensemble

# Define model definitions
defaults:
  - autoencoder_ensemble: sii
  - naive_ensemble: sii
  - plain_ensemble: sii
  - _self_
