---
params:
- name: lgbm
  model_class: LGBMRegressor
  params:
    n_estimators: 1000
    learning_rate: 0.01
    max_depth: 7
    num_leaves: 660
    min_data_in_leaf: 30
    lambda_l1: 45
    lambda_l2: 25
    bagging_fraction: 0.9
    bagging_freq: 1
    feature_fraction: 0.8
    random_state: 42
    verbose: -1
- name: xgb
  model_class: XGBRegressor
  params:
    n_estimators: 1000
    learning_rate: 0.007
    max_depth: 3
    subsample: 0.92
    colsample_bytree: 0.91
    reg_alpha: 98
    reg_lambda: 88
    # tree_method: exact
    min_child_weight: 9
    random_state: 42
    verbosity: 0
- name: catb
  model_class: CatBoostRegressor
  params:
    learning_rate: 0.015
    depth: 3
    subsample: 0.69
    colsample_bylevel: 0.565
    min_data_in_leaf: 88
    iterations: 400
    # l2_leaf_reg: 10
    verbose: 0
    allow_writing_files: false
    random_seed: 42
